import type {
  AgentRun,
  CeilingProgress,
  CeilingTriple,
  Credential,
  Decision,
  ManagedResource,
  ObservationFlags,
  SecretEntry,
  StudyState,
} from "../types";

/** Frozen clock for the study: matches the v7 PRFAQ launch narrative. */
export const STUDY_NOW = "2027-02-10T18:34:12Z";

export const PARENT_SCOPES = [
  "droplet:create",
  "droplet:read",
  "droplet:delete",
  "droplet:update",
  "volume:*",
  "inference:invoke",
  "spaces:read",
  "spaces:write",
  "billing:read",
] as const;

export const TASK_SCOPES = [
  "droplet:create",
  "droplet:read",
  "droplet:delete",
  "volume:*",
  "inference:invoke",
  "spaces:write",
] as const;

export const AGENT_ACTIONS = [
  { action: "Create Droplet", scope: "droplet:create" },
  { action: "Create Volume", scope: "volume:create" },
  { action: "Call inference", scope: "inference:invoke" },
] as const;

export const DEFAULT_CEILINGS: CeilingTriple = {
  actions: 40,
  resources: 3,
  inference_tokens: 500000,
  spend_usd: 25,
};

export const DEFAULT_OBSERVATIONS: ObservationFlags = {
  parentShownInHarness: false,
  childMintedOnceReused: false,
  pickedLongExpiry: false,
  triedToExtendChild: false,
  triedToRaiseCeilingFromAgent: false,
  revokedWithoutOpeningResources: false,
  treatedRevokeAsUndo: false,
  treatedCeilingAsSpend: false,
  usedDecisionRecord: false,
  wentToBillingFirst: false,
  derivedPerTask: false,
  hesitatedOnRevoke: false,
};

const ceil = (
  actionsUsed: number,
  resourcesUsed: number,
  tokensUsed: number,
  spendUsed?: number,
  max: CeilingTriple = DEFAULT_CEILINGS,
): CeilingProgress => ({
  actions: { used: actionsUsed, max: max.actions },
  resources: { used: resourcesUsed, max: max.resources },
  inference_tokens: { used: tokensUsed, max: max.inference_tokens },
  spend_usd: {
    used:
      spendUsed ??
      Math.min(max.spend_usd, Number((resourcesUsed * 7 + actionsUsed * 0.35).toFixed(2))),
    max: max.spend_usd,
  },
});

export const PARENT_CREDENTIAL: Credential = {
  id: "cred_parent_coding_agent",
  parent: "—",
  agent: "agent:coding-agent-prod",
  label: "coding-agent-prod",
  tenantId: null,
  scopes: [...PARENT_SCOPES],
  requestedScopes: [...PARENT_SCOPES],
  expiresAt: "2027-12-31T23:59:59Z",
  expiresInSeconds: 28000000,
  status: "active",
  ceilings: null,
  depth: 0,
  lastActivity: "2027-02-10T18:31:00Z",
  createdAt: "2026-08-14T09:00:00Z",
  kind: "parent",
  secret: "dop_v1_acme_parent_KEEP_IN_VAULT",
  secretRevealed: false,
};

export const CHILD_A: Credential = {
  id: "cred_01HQ8f21c",
  parent: "agent:coding-agent-prod",
  agent: "agent:coding-agent-prod",
  label: "task-8f21c",
  tenantId: "acme-user-a",
  scopes: [...TASK_SCOPES],
  requestedScopes: [...TASK_SCOPES, "billing:read"],
  expiresAt: "2027-02-10T18:41:00Z",
  expiresInSeconds: 600,
  status: "active",
  ceilings: { ...DEFAULT_CEILINGS },
  depth: 1,
  lastActivity: "2027-02-10T18:33:58Z",
  createdAt: "2027-02-10T18:31:00Z",
  kind: "child",
  secret: "dop_c_8f21c_SHOWN_ONCE",
  secretRevealed: true,
};

export const CHILD_B: Credential = {
  id: "cred_01HQb19d4",
  parent: "agent:coding-agent-prod",
  agent: "agent:coding-agent-prod",
  label: "task-b19d4",
  tenantId: "acme-user-b",
  scopes: [...TASK_SCOPES],
  requestedScopes: [...TASK_SCOPES],
  expiresAt: "2027-02-10T18:44:00Z",
  expiresInSeconds: 600,
  status: "active",
  ceilings: { ...DEFAULT_CEILINGS },
  depth: 1,
  lastActivity: "2027-02-10T18:33:40Z",
  createdAt: "2027-02-10T18:34:00Z",
  kind: "child",
  secret: "dop_c_b19d4_SHOWN_ONCE",
  secretRevealed: true,
};

export const SECRETS: SecretEntry[] = [
  {
    id: "vault-parent",
    name: "do/prod/coding-agent-parent",
    credentialId: PARENT_CREDENTIAL.id,
    kind: "parent",
    note: "Assumed secret manager. Parent lives here. The harness should never see this value.",
  },
];

export const RUNS: AgentRun[] = [
  {
    id: "run_a_8f21c",
    tenantId: "acme-user-a",
    label: "task-8f21c",
    mode: "self-hosted",
    status: "running",
    injectedCredentialId: CHILD_A.id,
    parentLeaked: false,
    stepIndex: 12,
    ceilings: { ...DEFAULT_CEILINGS },
    remaining: { actions: 2, resources: 0, inference_tokens: 212400, spend_usd: 3.2 },
    taskPrompt: "Stand up a staging box for tenant A (web + volume).",
  },
  {
    id: "run_b_b19d4",
    tenantId: "acme-user-b",
    label: "task-b19d4",
    mode: "self-hosted",
    status: "running",
    injectedCredentialId: CHILD_B.id,
    parentLeaked: false,
    stepIndex: 3,
    ceilings: { ...DEFAULT_CEILINGS },
    remaining: { actions: 37, resources: 2, inference_tokens: 487160, spend_usd: 18.4 },
    taskPrompt: "Refresh tenant B preview environment.",
  },
  {
    id: "run_a_managed",
    tenantId: "acme-user-a",
    label: "task-8f21c",
    mode: "managed",
    status: "ceiling_exhausted",
    injectedCredentialId: "cred_managed_8f21c",
    parentLeaked: false,
    stepIndex: 12,
    ceilings: { ...DEFAULT_CEILINGS },
    remaining: { actions: 0, resources: 0, inference_tokens: 212400, spend_usd: 0 },
    taskPrompt: "Stand up a staging box for tenant A (web + volume).",
  },
];

export const MANAGED_CHILD: Credential = {
  id: "cred_managed_8f21c",
  parent: "agent:coding-agent-prod",
  agent: "agent:coding-agent-prod",
  label: "task-8f21c",
  tenantId: "acme-user-a",
  scopes: [...TASK_SCOPES],
  requestedScopes: [...TASK_SCOPES],
  expiresAt: "2027-02-10T18:41:00Z",
  expiresInSeconds: 600,
  status: "active",
  ceilings: { ...DEFAULT_CEILINGS },
  depth: 1,
  lastActivity: "2027-02-10T18:33:58Z",
  createdAt: "2027-02-10T18:31:00Z",
  kind: "child",
  secret: "dop_c_managed_INJECTED",
  secretRevealed: true,
};

const d = (
  partial: Omit<Decision, "agent" | "parent"> & { agent?: string; parent?: string },
): Decision => ({
  agent: "agent:coding-agent-prod",
  parent: "agent:coding-agent-prod",
  ...partial,
});

/**
 * 16 scripted rows for tenant A plus 4 for tenant B.
 * Outcomes the study must be able to see: permitted create, ceiling_exhausted,
 * scope_denied, and (after the participant revokes) revoked.
 */
export const DECISIONS: Decision[] = [
  d({
    id: "dec_a_01",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:31:02Z",
    action: "Plan staging topology",
    scope: "inference:invoke",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(1, 0, 12840),
    detail: "Reserved 8,200 in + 20,000 max out; settled 12,840.",
  }),
  d({
    id: "dec_a_02",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:31:18Z",
    action: "Create Droplet",
    scope: "droplet:create",
    resourceId: "droplet-3182",
    resourceName: "staging-web-1",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(2, 1, 12840),
    detail: "s-2vcpu-4gb in nyc3.",
  }),
  d({
    id: "dec_a_03",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:31:22Z",
    action: "Create Volume",
    scope: "volume:create",
    resourceId: "vol-441",
    resourceName: "staging-data",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(3, 2, 12840),
    detail: "100 GiB, nyc3, attached to staging-web-1.",
  }),
  d({
    id: "dec_a_04",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:31:41Z",
    action: "Create Droplet",
    scope: "droplet:create",
    resourceId: "droplet-3183",
    resourceName: "staging-web-2",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(4, 3, 12840),
    detail: "s-2vcpu-4gb in nyc3. Resource ceiling 3 of 3 on Managed Agents.",
  }),
  d({
    id: "dec_a_05",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:32:05Z",
    action: "Re-plan after timeout",
    scope: "inference:invoke",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(5, 3, 34940),
    detail: "Agent treated a create acknowledgement as failure.",
  }),
  d({
    id: "dec_a_06",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:32:11Z",
    action: "Create Droplet",
    scope: "droplet:create",
    resourceId: "droplet-3184",
    resourceName: "staging-web-3",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(6, 3, 34940),
    detail: "Retry created a third droplet. Still billing.",
  }),
  d({
    id: "dec_a_07",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:32:28Z",
    action: "Read droplet",
    scope: "droplet:read",
    resourceId: "droplet-3182",
    resourceName: "staging-web-1",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(7, 3, 34940),
    detail: "Health check. Does not increment resource ceiling.",
  }),
  d({
    id: "dec_a_08",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:32:44Z",
    action: "Read billing",
    scope: "billing:read",
    outcome: "scope_denied",
    task: "task-8f21c",
    ceilings: ceil(7, 3, 34940),
    detail: "Parent holds billing:read; this child does not. Requested scope was omitted at derive.",
  }),
  d({
    id: "dec_a_09",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:32:51Z",
    action: "Re-plan retry #4",
    scope: "inference:invoke",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(8, 3, 61200),
    detail: "Loop continues. Operator has not revoked yet.",
  }),
  d({
    id: "dec_a_10",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:33:04Z",
    action: "Call inference",
    scope: "inference:invoke",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(9, 3, 61200),
    detail: "Agent asked what to create next.",
  }),
  d({
    id: "dec_a_11",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:33:19Z",
    action: "Create Volume",
    scope: "volume:create",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(38, 3, 287600),
    detail: "Retries 10–37 omitted. Mixed Droplet, Volume, and inference calls.",
  }),
  d({
    id: "dec_a_12",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:33:41Z",
    action: "Call inference",
    scope: "inference:invoke",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(39, 3, 287600),
    detail: "One action remaining on Managed Agents limits.",
  }),
  d({
    id: "dec_a_13",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:33:52Z",
    action: "Create Volume",
    scope: "volume:create",
    outcome: "permitted",
    task: "task-8f21c",
    ceilings: ceil(40, 3, 287600, 25),
    detail: "Action and $25 spend ceilings reached on this call.",
  }),
  d({
    id: "dec_a_14",
    credentialId: CHILD_A.id,
    tenantId: "acme-user-a",
    timestamp: "2027-02-10T18:33:58Z",
    action: "Create Droplet",
    scope: "droplet:create",
    outcome: "ceiling_exhausted",
    task: "task-8f21c",
    ceilings: ceil(40, 3, 287600, 25),
    detail:
      "403 ceiling_exhausted. Action and $25 spend ceilings reached after Droplet, Volume, and inference calls.",
  }),
  d({
    id: "dec_b_01",
    credentialId: CHILD_B.id,
    tenantId: "acme-user-b",
    timestamp: "2027-02-10T18:34:02Z",
    action: "Call inference",
    scope: "inference:invoke",
    outcome: "permitted",
    task: "task-b19d4",
    ceilings: null,
    detail: "Customer B is healthy. Must keep running if A is revoked.",
  }),
  d({
    id: "dec_b_02",
    credentialId: CHILD_B.id,
    tenantId: "acme-user-b",
    timestamp: "2027-02-10T18:34:08Z",
    action: "Create Droplet",
    scope: "droplet:create",
    resourceId: "droplet-5501",
    resourceName: "preview-api-1",
    outcome: "permitted",
    task: "task-b19d4",
    ceilings: null,
    detail: "s-1vcpu-2gb in sfo3.",
  }),
  d({
    id: "dec_b_03",
    credentialId: CHILD_B.id,
    tenantId: "acme-user-b",
    timestamp: "2027-02-10T18:34:11Z",
    action: "Create Volume",
    scope: "volume:create",
    resourceId: "vol-5502",
    resourceName: "preview-data",
    outcome: "permitted",
    task: "task-b19d4",
    ceilings: null,
    detail: "25 GiB in sfo3. Preview is up. Do not take this customer down.",
  }),
];

export const RESOURCES: ManagedResource[] = [
  {
    id: "droplet-3182",
    type: "droplet",
    name: "staging-web-1",
    tenantId: "acme-user-a",
    credentialId: CHILD_A.id,
    createdByDecisionId: "dec_a_02",
    stillBilling: true,
    hourlyUsd: 0.048,
    region: "nyc3",
    status: "running",
    size: "s-2vcpu-4gb",
  },
  {
    id: "droplet-3183",
    type: "droplet",
    name: "staging-web-2",
    tenantId: "acme-user-a",
    credentialId: CHILD_A.id,
    createdByDecisionId: "dec_a_04",
    stillBilling: true,
    hourlyUsd: 0.048,
    region: "nyc3",
    status: "running",
    size: "s-2vcpu-4gb",
  },
  {
    id: "droplet-3184",
    type: "droplet",
    name: "staging-web-3",
    tenantId: "acme-user-a",
    credentialId: CHILD_A.id,
    createdByDecisionId: "dec_a_06",
    stillBilling: true,
    hourlyUsd: 0.048,
    region: "nyc3",
    status: "running",
    size: "s-2vcpu-4gb",
  },
  {
    id: "vol-441",
    type: "volume",
    name: "staging-data",
    tenantId: "acme-user-a",
    credentialId: CHILD_A.id,
    createdByDecisionId: "dec_a_03",
    stillBilling: true,
    hourlyUsd: 0.01,
    region: "nyc3",
    status: "running",
    size: "100 GiB",
  },
  {
    id: "droplet-5501",
    type: "droplet",
    name: "preview-api-1",
    tenantId: "acme-user-b",
    credentialId: CHILD_B.id,
    createdByDecisionId: "dec_b_02",
    stillBilling: true,
    hourlyUsd: 0.018,
    region: "sfo3",
    status: "running",
    size: "s-1vcpu-2gb",
  },
  {
    id: "vol-5502",
    type: "volume",
    name: "preview-data",
    tenantId: "acme-user-b",
    credentialId: CHILD_B.id,
    createdByDecisionId: "dec_b_03",
    stillBilling: true,
    hourlyUsd: 0.004,
    region: "sfo3",
    status: "running",
    size: "25 GiB",
  },
];

export function createInitialState(): StudyState {
  return {
    nowIso: STUDY_NOW,
    exhaustVariant: "pause-and-approve",
    revokeCopyVariant: "revoke-credential",
    screen: "scenarios",
    demoStep: 0,
    walkthroughOpen: false,
    activeScenarioId: null,
    ownerEmail: "maya@acme.com",
    ownerOffboarded: false,
    selectedCredentialId: PARENT_CREDENTIAL.id,
    selectedDecisionFilter: "all",
    lastDerivedSecret: null,
    toast: null,
    pagerActive: false,
    observations: { ...DEFAULT_OBSERVATIONS },
    credentials: [
      { ...PARENT_CREDENTIAL },
      { ...CHILD_A },
      { ...CHILD_B },
      { ...MANAGED_CHILD },
    ],
    decisions: DECISIONS.map((row) => ({ ...row })),
    resources: RESOURCES.map((row) => ({ ...row })),
    runs: RUNS.map((row) => ({ ...row })),
    secrets: SECRETS.map((row) => ({ ...row })),
    eventLog: [
      "Seeded acme-user-a (runaway) and acme-user-b (healthy).",
      "Parent credential stored only in secret manager.",
    ],
  };
}

export const HAPPY_PATH_STEPS: Array<{
  action: string;
  scope: string;
  outcome: Decision["outcome"];
  detail: string;
  resource?: { id: string; type: ManagedResource["type"]; name: string; size: string; hourlyUsd: number };
}> = [
  {
    action: "Call inference",
    scope: "inference:invoke",
    outcome: "permitted",
    detail: "Agent plans the staging box.",
  },
  {
    action: "Create Droplet",
    scope: "droplet:create",
    outcome: "permitted",
    detail: "s-2vcpu-4gb in nyc3.",
    resource: {
      id: "droplet-new",
      type: "droplet",
      name: "staging-new-1",
      size: "s-2vcpu-4gb",
      hourlyUsd: 0.048,
    },
  },
  {
    action: "Create Volume",
    scope: "volume:create",
    outcome: "permitted",
    detail: "50 GiB attached.",
    resource: {
      id: "vol-new",
      type: "volume",
      name: "staging-new-data",
      size: "50 GiB",
      hourlyUsd: 0.005,
    },
  },
];
